public ${CLASSNAME}(CustomFieldValuePersister customFieldValuePersister, StringConverter stringConverter, GenericConfigManager genericConfigManager, MultiGroupConverter multiGroupConverter, PermissionManager permissionManager, JiraAuthenticationContext authenticationContext, GroupManager groupManager, FieldVisibilityManager fieldVisibilityManager) {
    super(customFieldValuePersister, stringConverter, genericConfigManager, multiGroupConverter, permissionManager, authenticationContext, groupManager, fieldVisibilityManager);
}
