public ${CLASSNAME}(PermissionManager permissionManager, JiraAuthenticationContext jiraAuthenticationContext, VersionManager versionManager, CustomFieldValuePersister customFieldValuePersister, GenericConfigManager genericConfigManager, VersionHelperBean versionHelperBean) {
    super(permissionManager, jiraAuthenticationContext, versionManager, customFieldValuePersister, genericConfigManager, versionHelperBean);
}
