public ${CLASSNAME}(CustomFieldValuePersister customFieldValuePersister, UserConverter userConverter, GenericConfigManager genericConfigManager, ApplicationProperties applicationProperties, JiraAuthenticationContext authenticationContext, UserPickerSearchService searchService) {
    super(customFieldValuePersister, userConverter, genericConfigManager, applicationProperties, authenticationContext, searchService);
}
